<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Country;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries = [
            ['name' => 'Afghanistan', 'code' => 'AFG'],
            ['name' => 'Albania', 'code' => 'ALB'],
            ['name' => 'Algeria', 'code' => 'DZA'],
            ['name' => 'Andorra', 'code' => 'AND'],
            ['name' => 'Angola', 'code' => 'AGO'],
            ['name' => 'Argentina', 'code' => 'ARG'],
            ['name' => 'Armenia', 'code' => 'ARM'],
            ['name' => 'Australia', 'code' => 'AUS'],
            ['name' => 'Austria', 'code' => 'AUT'],
            ['name' => 'Azerbaijan', 'code' => 'AZE'],
            ['name' => 'Bahamas', 'code' => 'BHS'],
            ['name' => 'Bahrain', 'code' => 'BHR'],
            ['name' => 'Bangladesh', 'code' => 'BGD'],
            ['name' => 'Barbados', 'code' => 'BRB'],
            ['name' => 'Belarus', 'code' => 'BLR'],
            ['name' => 'Belgium', 'code' => 'BEL'],
            ['name' => 'Belize', 'code' => 'BLZ'],
            ['name' => 'Benin', 'code' => 'BEN'],
            ['name' => 'Bhutan', 'code' => 'BTN'],
            ['name' => 'Bolivia', 'code' => 'BOL'],
            ['name' => 'Bosnia and Herzegovina', 'code' => 'BIH'],
            ['name' => 'Botswana', 'code' => 'BWA'],
            ['name' => 'Brazil', 'code' => 'BRA'],
            ['name' => 'Brunei', 'code' => 'BRN'],
            ['name' => 'България', 'code' => 'BGR'],
            ['name' => 'Burkina Faso', 'code' => 'BFA'],
            ['name' => 'Burundi', 'code' => 'BDI'],
            ['name' => 'Cambodia', 'code' => 'KHM'],
            ['name' => 'Cameroon', 'code' => 'CMR'],
            ['name' => 'Canada', 'code' => 'CAN'],
            ['name' => 'Cape Verde', 'code' => 'CPV'],
            ['name' => 'Central African Republic', 'code' => 'CAF'],
            ['name' => 'Chad', 'code' => 'TCD'],
            ['name' => 'Chile', 'code' => 'CHL'],
            ['name' => 'China', 'code' => 'CHN'],
            ['name' => 'Colombia', 'code' => 'COL'],
            ['name' => 'Comoros', 'code' => 'COM'],
            ['name' => 'Congo', 'code' => 'COG'],
            ['name' => 'Costa Rica', 'code' => 'CRI'],
            ['name' => 'Croatia', 'code' => 'HRV'],
            ['name' => 'Cuba', 'code' => 'CUB'],
            ['name' => 'Cyprus', 'code' => 'CYP'],
            ['name' => 'Czech Republic', 'code' => 'CZE'],
            ['name' => 'Denmark', 'code' => 'DNK'],
            ['name' => 'Djibouti', 'code' => 'DJI'],
            ['name' => 'Dominica', 'code' => 'DMA'],
            ['name' => 'Dominican Republic', 'code' => 'DOM'],
            ['name' => 'Ecuador', 'code' => 'ECU'],
            ['name' => 'Egypt', 'code' => 'EGY'],
            ['name' => 'El Salvador', 'code' => 'SLV'],
            ['name' => 'Equatorial Guinea', 'code' => 'GNQ'],
            ['name' => 'Eritrea', 'code' => 'ERI'],
            ['name' => 'Estonia', 'code' => 'EST'],
            ['name' => 'Ethiopia', 'code' => 'ETH'],
            ['name' => 'Fiji', 'code' => 'FJI'],
            ['name' => 'Finland', 'code' => 'FIN'],
            ['name' => 'France', 'code' => 'FRA'],
            ['name' => 'Gabon', 'code' => 'GAB'],
            ['name' => 'Gambia', 'code' => 'GMB'],
            ['name' => 'Georgia', 'code' => 'GEO'],
            ['name' => 'Germany', 'code' => 'DEU'],
            ['name' => 'Ghana', 'code' => 'GHA'],
            ['name' => 'Greece', 'code' => 'GRC'],
            ['name' => 'Grenada', 'code' => 'GRD'],
            ['name' => 'Guatemala', 'code' => 'GTM'],
            ['name' => 'Guinea', 'code' => 'GIN'],
            ['name' => 'Guinea-Bissau', 'code' => 'GNB'],
            ['name' => 'Guyana', 'code' => 'GUY'],
            ['name' => 'Haiti', 'code' => 'HTI'],
            ['name' => 'Honduras', 'code' => 'HND'],
            ['name' => 'Hungary', 'code' => 'HUN'],
            ['name' => 'Iceland', 'code' => 'ISL'],
            ['name' => 'India', 'code' => 'IND'],
            ['name' => 'Indonesia', 'code' => 'IDN'],
            ['name' => 'Iran', 'code' => 'IRN'],
            ['name' => 'Iraq', 'code' => 'IRQ'],
            ['name' => 'Ireland', 'code' => 'IRL'],
            ['name' => 'Israel', 'code' => 'ISR'],
            ['name' => 'Italy', 'code' => 'ITA'],
            ['name' => 'Jamaica', 'code' => 'JAM'],
            ['name' => 'Japan', 'code' => 'JPN'],
            ['name' => 'Jordan', 'code' => 'JOR'],
            ['name' => 'Kazakhstan', 'code' => 'KAZ'],
            ['name' => 'Kenya', 'code' => 'KEN'],
            ['name' => 'Kiribati', 'code' => 'KIR'],
            ['name' => 'Kuwait', 'code' => 'KWT'],
            ['name' => 'Kyrgyzstan', 'code' => 'KGZ'],
            ['name' => 'Laos', 'code' => 'LAO'],
            ['name' => 'Latvia', 'code' => 'LVA'],
            ['name' => 'Lebanon', 'code' => 'LBN'],
            ['name' => 'Lesotho', 'code' => 'LSO'],
            ['name' => 'Liberia', 'code' => 'LBR'],
            ['name' => 'Libya', 'code' => 'LBY'],
            ['name' => 'Liechtenstein', 'code' => 'LIE'],
            ['name' => 'Lithuania', 'code' => 'LTU'],
            ['name' => 'Luxembourg', 'code' => 'LUX'],
            ['name' => 'Madagascar', 'code' => 'MDG'],
            ['name' => 'Malawi', 'code' => 'MWI'],
            ['name' => 'Malaysia', 'code' => 'MYS'],
            ['name' => 'Maldives', 'code' => 'MDV'],
            ['name' => 'Mali', 'code' => 'MLI'],
            ['name' => 'Malta', 'code' => 'MLT'],
            ['name' => 'Marshall Islands', 'code' => 'MHL'],
            ['name' => 'Mauritania', 'code' => 'MRT'],
            ['name' => 'Mauritius', 'code' => 'MUS'],
            ['name' => 'Mexico', 'code' => 'MEX'],
            ['name' => 'Micronesia', 'code' => 'FSM'],
            ['name' => 'Moldova', 'code' => 'MDA'],
            ['name' => 'Monaco', 'code' => 'MCO'],
            ['name' => 'Mongolia', 'code' => 'MNG'],
            ['name' => 'Montenegro', 'code' => 'MNE'],
            ['name' => 'Morocco', 'code' => 'MAR'],
            ['name' => 'Mozambique', 'code' => 'MOZ'],
            ['name' => 'Myanmar', 'code' => 'MMR'],
            ['name' => 'Namibia', 'code' => 'NAM'],
            ['name' => 'Nauru', 'code' => 'NRU'],
            ['name' => 'Nepal', 'code' => 'NPL'],
            ['name' => 'Netherlands', 'code' => 'NLD'],
            ['name' => 'New Zealand', 'code' => 'NZL'],
            ['name' => 'Nicaragua', 'code' => 'NIC'],
            ['name' => 'Niger', 'code' => 'NER'],
            ['name' => 'Nigeria', 'code' => 'NGA'],
            ['name' => 'North Korea', 'code' => 'PRK'],
            ['name' => 'North Macedonia', 'code' => 'MKD'],
            ['name' => 'Norway', 'code' => 'NOR'],
            ['name' => 'Oman', 'code' => 'OMN'],
            ['name' => 'Pakistan', 'code' => 'PAK'],
            ['name' => 'Palau', 'code' => 'PLW'],
            ['name' => 'Palestine', 'code' => 'PSE'],
            ['name' => 'Panama', 'code' => 'PAN'],
            ['name' => 'Papua New Guinea', 'code' => 'PNG'],
            ['name' => 'Paraguay', 'code' => 'PRY'],
            ['name' => 'Peru', 'code' => 'PER'],
            ['name' => 'Philippines', 'code' => 'PHL'],
            ['name' => 'Poland', 'code' => 'POL'],
            ['name' => 'Portugal', 'code' => 'PRT'],
            ['name' => 'Qatar', 'code' => 'QAT'],
            ['name' => 'România', 'code' => 'ROU'],
            ['name' => 'Russia', 'code' => 'RUS'],
            ['name' => 'Rwanda', 'code' => 'RWA'],
            ['name' => 'Samoa', 'code' => 'WSM'],
            ['name' => 'San Marino', 'code' => 'SMR'],
            ['name' => 'Saudi Arabia', 'code' => 'SAU'],
            ['name' => 'Senegal', 'code' => 'SEN'],
            ['name' => 'Serbia', 'code' => 'SRB'],
            ['name' => 'Singapore', 'code' => 'SGP'],
            ['name' => 'Slovakia', 'code' => 'SVK'],
            ['name' => 'Slovenia', 'code' => 'SVN'],
            ['name' => 'Somalia', 'code' => 'SOM'],
            ['name' => 'South Africa', 'code' => 'ZAF'],
            ['name' => 'South Korea', 'code' => 'KOR'],
            ['name' => 'Spain', 'code' => 'ESP'],
            ['name' => 'Sri Lanka', 'code' => 'LKA'],
            ['name' => 'Sudan', 'code' => 'SDN'],
            ['name' => 'Sweden', 'code' => 'SWE'],
            ['name' => 'Switzerland', 'code' => 'CHE'],
            ['name' => 'Syria', 'code' => 'SYR'],
            ['name' => 'Taiwan', 'code' => 'TWN'],
            ['name' => 'Tajikistan', 'code' => 'TJK'],
            ['name' => 'Tanzania', 'code' => 'TZA'],
            ['name' => 'Thailand', 'code' => 'THA'],
            ['name' => 'Tunisia', 'code' => 'TUN'],
            ['name' => 'Turkey', 'code' => 'TUR'],
            ['name' => 'Turkmenistan', 'code' => 'TKM'],
            ['name' => 'Uganda', 'code' => 'UGA'],
            ['name' => 'Ukraine', 'code' => 'UKR'],
            ['name' => 'United Arab Emirates', 'code' => 'ARE'],
            ['name' => 'United Kingdom', 'code' => 'GBR'],
            ['name' => 'United States', 'code' => 'USA'],
            ['name' => 'Uruguay', 'code' => 'URY'],
            ['name' => 'Uzbekistan', 'code' => 'UZB'],
            ['name' => 'Venezuela', 'code' => 'VEN'],
            ['name' => 'Vietnam', 'code' => 'VNM'],
            ['name' => 'Yemen', 'code' => 'YEM'],
            ['name' => 'Zambia', 'code' => 'ZMB'],
            ['name' => 'Zimbabwe', 'code' => 'ZWE'],
        ];

        foreach ($countries as $country) {
            Country::create($country);
        }
    }
}
