<?php

namespace App\Services;

use App\Models\Candidate;
use App\Models\CandidateCvPhoto;
use App\Models\Category;
use App\Models\File;
use App\Models\Role;
use Illuminate\Support\Facades\Storage;
use PhpOffice\PhpWord\TemplateProcessor;

class CvDocxGeneratorService
{
    protected string $templatePath;

    public function __construct()
    {
        $this->templatePath = storage_path('app/templates/cv_template.docx');
    }

    /**
     * Generate CV DOCX for a candidate and save it to their files
     */
    public function generateAndSaveCv(Candidate $candidate, ?int $contractId = null): ?File
    {
        try {
            $docxPath = $this->generateCv($candidate);

            if (!$docxPath) {
                return null;
            }

            // Find or create the "files from agent" category for this candidate
            $category = $this->getOrCreateCvCategory($candidate);

            // If no contract ID provided, try to get the active contract
            if (!$contractId) {
                $activeContract = $candidate->contracts()->where('is_active', true)->first();
                $contractId = $activeContract?->id;
            }

            // Create file record
            $file = new File();
            $file->fileName = 'CV_' . $this->sanitizeFileName($candidate->fullName ?? $candidate->fullNameCyrillic ?? 'Candidate') . '.docx';
            $file->filePath = $docxPath;
            $file->candidate_id = $candidate->id;
            $file->contract_id = $contractId;
            $file->category_id = $category->id;
            $file->autoGenerated = 1;
            $file->company_restriction = 0;
            $file->save();

            return $file;
        } catch (\Exception $e) {
            \Log::error('CV Generation failed: ' . $e->getMessage());
            return null;
        }
    }

    /**
     * Generate CV DOCX file
     */
    public function generateCv(Candidate $candidate): ?string
    {
        if (!file_exists($this->templatePath)) {
            \Log::error('CV template not found at: ' . $this->templatePath);
            return null;
        }

        $templateProcessor = new TemplateProcessor($this->templatePath);

        // Personal Information
        $this->setPersonalInfo($templateProcessor, $candidate);

        // Passport Data
        $this->setPassportData($templateProcessor, $candidate);

        // Education
        $this->setEducation($templateProcessor, $candidate);

        // Driving License
        $this->setDrivingLicense($templateProcessor, $candidate);

        // Experience
        $this->setExperience($templateProcessor, $candidate);

        // Languages
        $this->setLanguages($templateProcessor, $candidate);

        // Comments
        $templateProcessor->setValue('comments', $candidate->notes ?? '');

        // Candidate Photo
        $this->setCandidatePhoto($templateProcessor, $candidate);

        // CV Photos (workplace, diploma, driving license) - conditionally show sections
        $this->setCvPhotosSection($templateProcessor, $candidate);

        // Generate unique filename
        $fileName = 'cv_' . $candidate->id . '_' . time() . '.docx';
        $relativePath = 'files/' . $fileName;
        $fullPath = storage_path('app/public/' . $relativePath);

        // Ensure directory exists
        $dir = dirname($fullPath);
        if (!is_dir($dir)) {
            mkdir($dir, 0755, true);
        }

        $templateProcessor->saveAs($fullPath);

        return $relativePath;
    }

    /**
     * Set personal information in template
     */
    protected function setPersonalInfo(TemplateProcessor $template, Candidate $candidate): void
    {
        $template->setValue('first_name', $candidate->fullName ?? '');
        $template->setValue('last_name', $candidate->fullNameCyrillic ?? '');
        $template->setValue('address_of_residence', $candidate->addressOfResidence ?? $candidate->address ?? '');
        $template->setValue('whatsapp_phone', $candidate->phoneNumber ?? '');

        // Gender checkboxes
        $template->setValue('gender_male', $candidate->gender === 'male' ? '☑' : '☐');
        $template->setValue('gender_female', $candidate->gender === 'female' ? '☑' : '☐');

        $template->setValue('date_of_birth', $this->formatDate($candidate->birthday));
        $template->setValue('marital_status', $this->formatMaritalStatus($candidate->martialStatus, $candidate->children_info));
        $template->setValue('height', $candidate->height ?? '');
        $template->setValue('weight', $candidate->weight ?? '');
        $template->setValue('citizenship', $candidate->nationality ?? '');
        $template->setValue('chronic_diseases', $candidate->chronic_diseases ?? '');
        $template->setValue('country_of_visa', $candidate->country_of_visa_application ?? '');
    }

    /**
     * Set passport data in template
     */
    protected function setPassportData(TemplateProcessor $template, Candidate $candidate): void
    {
        $passportInfo = [];
        $passport = $candidate->passportRecord;

        if ($passport?->passport_number) {
            $passportInfo[] = 'Number: ' . $passport->passport_number;
        }
        if ($passport?->issued_by) {
            $passportInfo[] = 'Issued by: ' . $passport->issued_by;
        }
        if ($passport?->issue_date) {
            $passportInfo[] = 'Issued: ' . $this->formatDate($passport->issue_date);
        }
        if ($passport?->expiry_date) {
            $passportInfo[] = 'Valid until: ' . $this->formatDate($passport->expiry_date);
        }

        $template->setValue('passport_data', implode(', ', $passportInfo));
    }

    /**
     * Set education in template (supports multiple entries)
     */
    protected function setEducation(TemplateProcessor $template, Candidate $candidate): void
    {
        $educations = $candidate->education()->get();

        if ($educations->count() > 0) {
            // Clone row for each education entry
            $template->cloneRow('edu_institution', $educations->count());

            foreach ($educations as $index => $edu) {
                $rowNum = $index + 1;
                $template->setValue("edu_institution#{$rowNum}", $edu->school_name ?? '');
                $template->setValue("edu_speciality#{$rowNum}", $edu->field_of_study ?? '');
                $template->setValue("edu_year#{$rowNum}", $this->extractYear($edu->end_date));
            }
        } else {
            // No education - use legacy fields or empty
            $template->cloneRow('edu_institution', 1);
            $template->setValue('edu_institution#1', $candidate->education ?? '');
            $template->setValue('edu_speciality#1', $candidate->specialty ?? '');
            $template->setValue('edu_year#1', '');
        }
    }

    /**
     * Set driving license in template
     */
    protected function setDrivingLicense(TemplateProcessor $template, Candidate $candidate): void
    {
        $hasLicense = $candidate->has_driving_license ?? false;

        $template->setValue('driving_yes', $hasLicense ? '☑' : '☐');
        $template->setValue('driving_no', !$hasLicense ? '☑' : '☐');
        $template->setValue('driving_category', $candidate->driving_license_category ?? '');
        $template->setValue('driving_expiry', $this->formatDate($candidate->driving_license_expiry));
        $template->setValue('driving_country', $candidate->driving_license_country ?? '');
    }

    /**
     * Set experience in template (supports multiple entries)
     */
    protected function setExperience(TemplateProcessor $template, Candidate $candidate): void
    {
        $experiences = $candidate->experience()->orderBy('start_date', 'desc')->get();

        if ($experiences->count() > 0) {
            // Clone row for each experience entry
            $template->cloneRow('exp_company', $experiences->count());

            foreach ($experiences as $index => $exp) {
                $rowNum = $index + 1;
                $template->setValue("exp_company#{$rowNum}", $exp->company_name ?? '');
                $template->setValue("exp_position#{$rowNum}", $exp->position ?? '');
                $template->setValue("exp_duration#{$rowNum}", $this->formatDuration($exp->start_date, $exp->end_date));
                $template->setValue("exp_responsibilities#{$rowNum}", $exp->responsibilities ?? '');
            }
        } else {
            // No experience - show empty row
            $template->cloneRow('exp_company', 1);
            $template->setValue('exp_company#1', '');
            $template->setValue('exp_position#1', '');
            $template->setValue('exp_duration#1', '');
            $template->setValue('exp_responsibilities#1', '');
        }
    }

    /**
     * Set languages in template
     */
    protected function setLanguages(TemplateProcessor $template, Candidate $candidate): void
    {
        // English - display level text
        $template->setValue('english_level', $this->formatLanguageLevel($candidate->english_level));

        // Russian - display level text
        $template->setValue('russian_level', $this->formatLanguageLevel($candidate->russian_level));

        // Other language
        $template->setValue('other_language', $candidate->other_language ?? '');
        $template->setValue('other_language_level', $this->formatLanguageLevel($candidate->other_language_level));
    }

    /**
     * Format language level for display
     */
    protected function formatLanguageLevel(?string $level): string
    {
        return match ($level) {
            'none' => 'No knowledge',
            'elementary' => 'Elementary',
            'average' => 'Average',
            'advanced' => 'Advanced',
            default => '',
        };
    }

    /**
     * Set candidate photo in template
     */
    protected function setCandidatePhoto(TemplateProcessor $template, Candidate $candidate): void
    {
        if ($candidate->personPicturePath) {
            $imagePath = storage_path('app/public/' . $candidate->personPicturePath);

            if (file_exists($imagePath)) {
                try {
                    $template->setImageValue('candidate_photo', [
                        'path' => $imagePath,
                        'width' => 200,
                        'height' => 260,
                        'ratio' => true,
                        'wrappingStyle' => 'inline',
                    ]);
                    return;
                } catch (\Exception $e) {
                    \Log::warning('Failed to set candidate photo: ' . $e->getMessage());
                }
            }
        }

        // If no photo or failed, replace with empty text
        $template->setValue('candidate_photo', '(No photo available)');
    }

    /**
     * Set CV photos section - conditionally shows/hides based on available photos
     */
    protected function setCvPhotosSection(TemplateProcessor $template, Candidate $candidate): void
    {
        $workplacePhotos = $candidate->workplacePhotos()->orderBy('sort_order')->get();
        $diplomaPhotos = $candidate->diplomaPhotos()->orderBy('sort_order')->get();
        $drivingLicensePhoto = $candidate->drivingLicensePhoto;

        $hasWorkplacePhotos = $workplacePhotos->count() > 0;
        $hasDiplomaPhotos = $diplomaPhotos->count() > 0;
        $hasDrivingLicensePhoto = $drivingLicensePhoto && $drivingLicensePhoto->file_path;
        $hasAnyPhotos = $hasWorkplacePhotos || $hasDiplomaPhotos || $hasDrivingLicensePhoto;

        // Set section header - only show if there are any photos
        $template->setValue('photos_section_header', $hasAnyPhotos ? 'PHOTOS' : '');

        // Workplace photos section
        $template->setValue('workplace_photos_label', $hasWorkplacePhotos ? 'Workplace Photos:' : '');
        for ($i = 1; $i <= 4; $i++) {
            $photo = $workplacePhotos->get($i - 1);
            $this->setPhotoOrEmpty($template, "workplace_photo_{$i}", $photo);
        }

        // Diploma photos section
        $template->setValue('diploma_photos_label', $hasDiplomaPhotos ? 'Diploma/Certificate Photos:' : '');
        for ($i = 1; $i <= 2; $i++) {
            $photo = $diplomaPhotos->get($i - 1);
            $this->setPhotoOrEmpty($template, "diploma_photo_{$i}", $photo);
        }

        // Driving license photo section
        $template->setValue('driving_license_photo_label', $hasDrivingLicensePhoto ? 'Driving License Photo:' : '');
        $this->setPhotoOrEmpty($template, 'driving_license_photo', $drivingLicensePhoto);
    }

    /**
     * Set a photo in template or empty string if no photo
     * @param TemplateProcessor $template
     * @param string $placeholder
     * @param CandidateCvPhoto|null $photo
     */
    protected function setPhotoOrEmpty(TemplateProcessor $template, string $placeholder, $photo): void
    {
        if ($photo instanceof CandidateCvPhoto && $photo->file_path) {
            $imagePath = storage_path('app/public/' . $photo->file_path);

            if (file_exists($imagePath) && $this->isImageFile($imagePath)) {
                try {
                    $template->setImageValue($placeholder, [
                        'path' => $imagePath,
                        'width' => 350,
                        'height' => 280,
                        'ratio' => true,
                        'wrappingStyle' => 'inline',
                    ]);
                    return;
                } catch (\Exception $e) {
                    \Log::warning("Failed to set photo {$placeholder}: " . $e->getMessage());
                }
            }
        }

        $template->setValue($placeholder, '');
    }

    /**
     * Check if file is an image (not PDF)
     */
    protected function isImageFile(string $path): bool
    {
        $extension = strtolower(pathinfo($path, PATHINFO_EXTENSION));
        return in_array($extension, ['jpg', 'jpeg', 'png', 'gif', 'bmp']);
    }

    /**
     * Get or create "files from agent" category for candidate
     */
    protected function getOrCreateCvCategory(Candidate $candidate): Category
    {
        // Use existing "files from agent" category if it exists
        $category = Category::where('candidate_id', $candidate->id)
            ->where('nameOfCategory', 'files from agent')
            ->first();

        if (!$category) {
            $category = new Category();
            $category->candidate_id = $candidate->id;
            $category->nameOfCategory = 'files from agent';
            $category->isGenerated = 0;
            $category->save();
            $category->visibleToRoles()->attach([
                Role::AGENT,
                Role::GENERAL_MANAGER,
                Role::MANAGER,
                Role::OFFICE,
                Role::HR,
                Role::OFFICE_MANAGER,
                Role::RECRUITERS,
                Role::FINANCE,
            ]);
        }

        return $category;
    }

    /**
     * Format date for display
     */
    protected function formatDate($date): string
    {
        if (!$date) {
            return '';
        }

        try {
            return \Carbon\Carbon::parse($date)->format('d.m.Y');
        } catch (\Exception $e) {
            return (string) $date;
        }
    }

    /**
     * Extract year from date
     */
    protected function extractYear($date): string
    {
        if (!$date) {
            return '';
        }

        try {
            // Handle both date string and year integer
            if (is_numeric($date)) {
                return (string) $date;
            }
            return \Carbon\Carbon::parse($date)->format('Y');
        } catch (\Exception $e) {
            return '';
        }
    }

    /**
     * Format duration between two dates
     */
    protected function formatDuration($startDate, $endDate): string
    {
        $start = $this->extractYear($startDate);
        $end = $endDate ? $this->extractYear($endDate) : 'Present';

        if ($start && $end) {
            return $start . ' - ' . $end;
        }

        return $start ?: $end;
    }

    /**
     * Format marital status with children info
     */
    protected function formatMaritalStatus(?string $status, ?string $childrenInfo): string
    {
        $result = $status ?? '';

        if ($childrenInfo) {
            $result .= ($result ? ' / ' : '') . $childrenInfo;
        }

        return $result;
    }

    /**
     * Sanitize filename
     */
    protected function sanitizeFileName(string $name): string
    {
        return preg_replace('/[^A-Za-z0-9_\-]/', '_', $name);
    }
}
