<?php

namespace App\Http\Controllers;

use App\Jobs\SendEmailForArrivalCandidates;
use App\Jobs\SendEmailForArrivalStatusCandidates;
use App\Models\Status;
use App\Services\InvoiceService;
use App\Services\AgentInvoiceService;
use App\Traits\HasRolePermissions;
use App\Jobs\SendEmailToCompany;
use App\Models\Arrival;
use App\Models\ArrivalCandidate;
use App\Models\File;
use App\Services\File\FileOperationService;
use App\Models\CalendarEvent;
use App\Models\Candidate;
use App\Models\Category;
use App\Models\Statushistory;
use Carbon\Carbon;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Mail;

class ArrivalController extends Controller
{
    use HasRolePermissions;



    /**
     * Display a listing of the resource.
     *
     * @return JsonResponse
     */
    public function index(): JsonResponse
    {
        try {
            if($this->isStaff()) {
                $arrivals = Arrival::with(['company', 'candidate', 'files'])->get();
            } else {
                $arrivals = []; // Here i need to implement the logic to get the arrivals for the Company
            }

            return response()->json([
                'message' => 'Arrivals retrieved successfully',
                'arrivals' => $arrivals
            ]);
        } catch (\Exception $e) {
            return response()->json($e->getMessage());
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Services\File\FileOperationService  $fileOperationService
     * @return \Illuminate\Http\JsonResponse
     */
    public function store(Request $request, FileOperationService $fileOperationService)
    {
        if (!$this->isStaff()) {
            return response()->json(['error' => 'You are not authorized to create an arrival'], 403);
        }

        try {
            DB::beginTransaction();

            $candidateId = $request->candidate_id;

            $arrival = Arrival::firstOrNew(['candidate_id' => $candidateId]);
            $arrivalDate = $request->arrival_date;

            $arrival->fill([
                'company_id'       => $request->company_id,
                'arrival_date'     => $arrivalDate,
                'arrival_time'     => $request->arrival_time,
                'arrival_location' => $request->arrival_location,
                'arrival_flight'   => $request->arrival_flight,
                'where_to_stay'    => $request->where_to_stay,
                'phone_number'     => $request->phone_number,
            ]);

            // Ensure category exists first to get ID for file
            $category = Category::firstOrCreate(
                [
                    'candidate_id'     => $candidateId,
                    'nameOfCategory'   => Category::ARRIVAL_DOCUMENTS,
                ],
                [
                    'role_id'      => 2,
                    'isGenerated'  => 0,
                ]
            );

            if ($request->hasFile('ticket_files')) {
                foreach ($request->file('ticket_files') as $file) {
                    $directory = 'candidate/' . $candidateId . '/documents/' . $category->id;
                    $filePath = $fileOperationService->uploadFile($file, $directory);
                    
                    File::create([
                         'candidate_id' => $candidateId,
                         'arrival_id' => $arrival->id,
                         'category_id' => $category->id,
                         'filePath' => $filePath,
                         'fileName' => $file->getClientOriginalName(),
                         'autoGenerated' => 0,
                         'deleteFile' => 0,
                         'company_restriction' => 0,
                    ]);
                }
            }

            $arrival->save();

            // Status ID for "Arrival Expected"
            $statusId = Status::ARRIVAL_EXPECTED;
            $sendEmail = $request->sendEmail ?? false;

            if (!in_array($statusId, [
                Status::TERMINATED_CONTRACT,
                Status::REFUSED_MIGRATION,
                Status::REFUSED_CANDIDATE,
                Status::REFUSED_EMPLOYER,
                Status::REFUSED_BY_MIGRATION_OFFICE
            ])) {
                $allStatuses = Status::where('order', '<=', Status::find($statusId)->order)
                    ->pluck('id')
                    ->toArray();
            } else {
                $allStatuses = [$statusId];
            }


            foreach ($allStatuses as $status) {
                $existingStatus = Statushistory::where('candidate_id', $candidateId)
                    ->where('status_id', $status)
                    ->first();

                if (!$existingStatus) {
                    Statushistory::create([
                        'candidate_id' => $candidateId,
                        'status_id'    => $status,
                        'statusDate'   => $arrivalDate,
                        'description'  => 'Arrival Expected',
                    ]);

                    InvoiceService::saveInvoiceOnStatusChange($candidateId, $status, $arrivalDate);
                    AgentInvoiceService::saveAgentInvoiceOnStatusChange($candidateId, $status, $arrivalDate);
                }
            }

            // Update the candidate's current status (CRITICAL FIX!)
            $candidate = Candidate::find($candidateId);
            if ($candidate) {
                $candidate->status_id = $statusId;
                $candidate->save();
            }

            dispatch(new SendEmailForArrivalStatusCandidates($statusId, $candidateId, $arrivalDate, $sendEmail));

            // Create or update calendar event for arrival
            CalendarEvent::updateOrCreate(
                [
                    'type' => CalendarEvent::TYPE_ARRIVAL,
                    'candidate_id' => $candidateId,
                ],
                [
                    'title' => 'Пристигане',
                    'date' => $arrivalDate,
                    'time' => $request->arrival_time,
                    'company_id' => $candidate->company_id,
                    'created_by' => Auth::id(),
                ]
            );

            DB::commit();

            return response()->json([
                'success' => true,
                'message' => 'Информацията за пристигане беше запазена успешно',
                'arrival' => $arrival,
            ], 201);

        } catch (\Throwable $e) {
            DB::rollBack();
            return response()->json([
                'success' => false,
                'message' => 'Грешка при запазване на информацията за пристигане',
                'error' => $e->getMessage()
            ], 500);
        }
    }

    public function update(Request $request, $id, FileOperationService $fileOperationService)
    {
        if (!$this->isStaff()) {
            return response()->json(['error' => 'You are not authorized to update an arrival'], 403);
        }

        try {
            DB::beginTransaction();

            $arrival = Arrival::findOrFail($id);
            $candidateId = $arrival->candidate_id;

            $arrivalDate = $request->arrival_date;

            // Ensure category exists
            $category = Category::firstOrCreate(
                [
                    'candidate_id'   => $candidateId,
                    'nameOfCategory' => Category::ARRIVAL_DOCUMENTS,
                ],
                [
                    'role_id'     => 2,
                    'isGenerated' => 0,
                ]
            );

            if ($request->hasFile('ticket_files')) {
                foreach ($request->file('ticket_files') as $file) {
                    $directory = 'candidate/' . $candidateId . '/documents/' . $category->id;
                    $filePath = $fileOperationService->uploadFile($file, $directory);
                    
                    File::create([
                         'candidate_id' => $candidateId,
                         'arrival_id' => $arrival->id,
                         'category_id' => $category->id,
                         'filePath' => $filePath,
                         'fileName' => $file->getClientOriginalName(),
                         'autoGenerated' => 0,
                         'deleteFile' => 0,
                         'company_restriction' => 0,
                    ]);
                }
            }
            
            // Handle deletions
            if ($request->filled('delete_file_ids')) {
                $filesToDelete = File::whereIn('id', $request->delete_file_ids)
                                     ->where('arrival_id', $arrival->id)
                                     ->get();
                                     
                foreach ($filesToDelete as $file) {
                    $fileOperationService->deleteFile($file->filePath);
                    $file->delete();
                }
            }

            // Update Arrival fields
            $arrival->update([
                'company_id'       => $request->company_id,
                'arrival_date'     => $arrivalDate,
                'arrival_time'     => $request->arrival_time,
                'arrival_location' => $request->arrival_location,
                'arrival_flight'   => $request->arrival_flight,
                'where_to_stay'    => $request->where_to_stay,
                'phone_number'     => $request->phone_number,
            ]);

            // Status ID for "Arrival Expected"
            $statusId = Status::ARRIVAL_EXPECTED;
            $sendEmail = $request->sendEmail ?? false;

            $candidate = Candidate::find($candidateId);

            // Update calendar event for arrival
            CalendarEvent::updateOrCreate(
                [
                    'type' => CalendarEvent::TYPE_ARRIVAL,
                    'candidate_id' => $candidateId,
                ],
                [
                    'title' => 'Пристигане',
                    'date' => $arrivalDate,
                    'time' => $request->arrival_time,
                    'company_id' => $candidate?->company_id,
                    'created_by' => Auth::id(),
                ]
            );
            
            // Only send email if checkbox was checked
            dispatch(new SendEmailForArrivalStatusCandidates($statusId, $candidateId, $arrivalDate, $sendEmail));

            DB::commit();

            return response()->json([
                'message' => 'Arrival updated successfully',
                'arrival' => $arrival,
            ], 200);

        } catch (\Throwable $e) {
            DB::rollBack();
            return response()->json(['error' => $e->getMessage()], 500);
        }
    }

    public function destroy($id): JsonResponse
    {
        if ($this->isStaff()) {
            try {
                $arrivalCandidates = ArrivalCandidate::where('arrival_id', $id)->first();
                if ($arrivalCandidates) {
                    $arrivalCandidates->delete();
                }

                $arrival = Arrival::find($id);
                if ($arrival) {
                    $arrival->delete();
                }

                return response()->json('Arrival deleted successfully');
            } catch (\Exception $e) {
                return response()->json($e->getMessage());
            }
        } else {
            return response()->json('You are not authorized to delete this arrival');
        }
    }
}
