<?php

namespace App\Http\Controllers;

use App\Models\Candidate;
use App\Models\Category;
use App\Models\File;
use App\Models\Position;
use App\Models\UserOwner;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\DB;

class CandidateController extends Controller
{

    //  public function script()
    //     {
    //         $candidates = Candidate::all();

    //         foreach ($candidates as $candidate) {
    //             if ($candidate->passportPath) {

    //                 $file = new File();
    //                 $file->candidate_id = $candidate->id;
    //                 $file->category_id = 8;
    //                 $file->fileName = $candidate->passportName;
    //                 $file->filePath = $candidate->passportPath;
    //                 $file->autoGenerated = 1;

    //                 $file->save();
    //             }
    //         }
    //     }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (Auth::user()->role_id == 1 || Auth::user()->role_id == 2) {
            $query = Candidate::with(['company', 'status', 'position'])->orderBy('id', 'desc');
        } else if (Auth::user()->role_id == 3) {
            $query = Candidate::where('company_id', '=', Auth::user()->company_id)
                ->where('type_id', '=', 1)->orderBy('id', 'desc');
        } else {
            return response()->json([
                'success' => false,
                'status' => 401,
                'data' => []
            ]);
        }
        $candidates = $query->paginate(25);

        return response()->json([
            'success' => true,
            'status' => 200,
            'data' => $candidates,
        ]);
    }


    public function employees()
    {
        if (Auth::user()->role_id == 1 || Auth::user()->role_id == 2) {
            $query = Candidate::with(['company', 'status', 'position'])->where('type_id', '=', 2)->orderBy('id', 'desc');
        } else if (Auth::user()->role_id == 3) {
            $query = Candidate::where('company_id', '=', Auth::user()->company_id)
                ->where('type_id', '=', 2);
        } else {
            return response()->json([
                'success' => false,
                'status' => 401,
                'data' => []
            ]);
        }
        $employees = $query->paginate(25);

        return response()->json([
            'success' => true,
            'status' => 200,
            'data' => $employees,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if (Auth::user()->role_id == 1 || Auth::user()->role_id == 2) {

            $person = new Candidate();

            $person->status_id = $request->status_id;
            $person->type_id = $request->type_id;
            $person->company_id = $request->company_id;
            $person->gender = $request->gender;
            $person->email = $request->email;
            $person->nationality = $request->nationality;
            $person->date = $request->date;
            $person->phoneNumber = $request->phoneNumber;
            $person->address = $request->address;
            $person->passport = $request->passport;
            $person->fullName = $request->fullName;
            $person->fullNameCyrillic = $request->fullNameCyrillic;
            $person->birthday = $request->birthday;
            $person->placeOfBirth = $request->placeOfBirth;
            $person->country = $request->country;
            $person->area = $request->area;
            $person->areaOfResidence = $request->areaOfResidence;
            $person->addressOfResidence = $request->addressOfResidence;
            $person->periodOfResidence = $request->periodOfResidence;
            $person->passportValidUntil = $request->passportValidUntil;
            $person->passportIssuedBy = $request->passportIssuedBy;
            $person->passportIssuedOn = $request->passportIssuedOn;
            $person->addressOfWork = $request->addressOfWork;
            $person->nameOfFacility = $request->nameOfFacility;
            $person->education = $request->education;
            $person->specialty = $request->specialty;
            $person->qualification = $request->qualification;
            $person->contractExtensionPeriod = $request->contractExtensionPeriod;
            $person->salary = $request->salary;
            $person->workingTime = $request->workingTime;
            $person->workingDays = $request->workingDays;
            $person->martialStatus = $request->martialStatus;
            $person->contractPeriod = $request->contractPeriod;
            $person->contractType = $request->contractType;
            $person->position_id = $request->position_id;
            $person->dossierNumber = $request->dossierNumber;
            $person->notes = $request->notes;
            $person->user_id = $request->user_id;


            if ($request->hasFile('personPassport')) {
                Storage::disk('public')->put('personPassports', $request->file('personPassport'));
                $name = Storage::disk('public')->put('personPassports', $request->file('personPassport'));
                $person->passportPath = $name;
                $person->passportName = $request->file('personPassport')->getClientOriginalName();
            }


            if ($request->hasFile('personPicture')) {
                Storage::disk('public')->put('personImages', $request->file('personPicture'));
                $name = Storage::disk('public')->put('companyImages', $request->file('personPicture'));
                $person->personPicturePath = $name;
                $person->personPictureName = $request->file('personPicture')->getClientOriginalName();
            }

            if ($person->save()) {

                $jobPositionDocument = Position::where('id', $request->position_id)->first();

                if ($jobPositionDocument->positionPath != Null) {
                    $file = new File();

                    $file->candidate_id = $person->id;
                    $file->category_id = 8;
                    $file->fileName = $jobPositionDocument->positionName;
                    $file->filePath = $jobPositionDocument->positionPath;
                    $file->autoGenerated = 1;
                    $file->deleteFile = 2;

                    $file->save();
                }

                return response()->json([
                    'success' => true,
                    'status' => 200,
                    'data' => $person,
                ]);
            } else {
                return response()->json([
                    'success' => false,
                    'status' => 500,
                    'data' => [],
                ]);
            }
        } else {
            return response()->json([
                'success' => false,
                'status' => 401,
                'data' => [],
            ]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Candidate  $candidate
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if(Auth::user()->role_id == 1 || Auth::user()->role_id == 2){
            $person = Candidate::where('id', '=', $id)->first();

            if(isset($person)){
                return response()->json([
                    'success' => true,
                    'status' => 200,
                    'data' => $person,
                ],200);
            } else {
                return response()->json([
                    'success' => true,
                    'status' => 500,
                    'data' => [],
                ],500);
            }
        }else if(Auth::user()->role_id == 3){
            $person = Candidate::where('id', '=', $id)->where('company_id', Auth::user()->company_id)->first();

            if(isset($person)){
                return response()->json([
                    'success' => true,
                    'status' => 200,
                    'data' => $person,
                ],200);
            } else {
                return response()->json([
                    'success' => true,
                    'status' => 500,
                    'data' => [],
                ],500);
            }
        }else if(Auth::user()->role_id == 5){
            $userOwners = UserOwner::where('user_id', '=', Auth::user()->id)->get();
            $userOwnersArray = [];
            $companiesIds = [];

            foreach ($userOwners as $userOwner) {
                array_push($userOwnersArray, $userOwner->company_id);
            }
            foreach ($userOwners as $userOwner) {
                array_push($companiesIds, $userOwner->company_id);
            }

            $person = Candidate::where('id', '=', $id)->whereIn('company_id', $userOwnersArray)->first();

            if(isset($person)){
                return response()->json([
                    'success' => true,
                    'status' => 200,
                    'data' => $person,
                    'companiesIds' => $companiesIds,
                ],200);
            } else {
                return response()->json([
                    'success' => true,
                    'status' => 500,
                    'data' => [],
                ],500);
            }
        }
    }

    public function showPerson($id)
    {
        if (Auth::user()->role_id == 1 || Auth::user()->role_id == 2) {
            $person = Candidate::where('id', '=', $id)->first();
        } else if (Auth::user()->role_id == 3) {
            $person = Candidate::where('id', '=', $id)->where('company_id', Auth::user()->company_id)->first();
        } else if (Auth::user()->role_id == 5) {
            $userOwners = UserOwner::where('user_id', '=', Auth::user()->id)->get();
            $userOwnersArray = [];
            foreach ($userOwners as $userOwner) {
                array_push($userOwnersArray, $userOwner->company_id);
            }
            $person = Candidate::where('id', '=', $id)->whereIn('company_id', $userOwnersArray)->first();
        }

        if (isset($person)) {
            return response()->json([
                'success' => true,
                'status' => 200,
                'data' => $person,
            ], 200);
        } else {
            return response()->json([
                'success' => true,
                'status' => 500,
                'data' => [],
            ], 500);
        }
    }



    public function showPersonNew($id)
    {
        if(Auth::user()->role_id == 1 || Auth::user()->role_id == 2){
        $person = DB::table('candidates')
            ->join('companies', 'companies.id', '=', 'candidates.company_id')
            ->where('candidates.id', $id)
            ->select('candidates.*', 'companies.nameOfCompany')->first();
        }else if(Auth::user()->role_id == 3){
            $person = DB::table('candidates')
            ->join('companies', 'companies.id', '=', 'candidates.company_id')
            ->where('candidates.id', $id)
            ->where('candidates.company_id', Auth::user()->company_id)
            ->select('candidates.*', 'companies.nameOfCompany')->first();
        }else if(Auth::user()->role_id == 5){
            $userOwners = UserOwner::where('user_id', '=', Auth::user()->id)->get();
            $userOwnersArray = [];
            foreach ($userOwners as $userOwner) {
                array_push($userOwnersArray, $userOwner->company_id);
            }
            $person = DB::table('candidates')
            ->join('companies', 'companies.id', '=', 'candidates.company_id')
            ->where('candidates.id', $id)
            ->whereIn('candidates.company_id', $userOwnersArray)
            ->select('candidates.*', 'companies.nameOfCompany')->first();
        }
        if(isset($person)){
            return response()->json([
                'success' => true,
                'status' => 200,
                'data' => $person,
            ], 200);
        }else{
            return response()->json([
                'success' => true,
                'status' => 500,
                'data' => [],
            ], 500);
        }
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Candidate  $candidate
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        if (Auth::user()->role_id == 1 || Auth::user()->role_id == 2) {

            $files = File::where('candidate_id', '=', $id)->where('autoGenerated', '=', 1)->where('deleteFile', '0')->get();


            foreach ($files as $file) {
                unlink(storage_path() . '/app/public/' . $file->filePath);
                $file->delete();
            }

            if ($request->education === 'null') {
                $education = Null;
            } else {
                $education = $request->education;
            }

            if ($request->specialty === 'null') {
                $specialty = Null;
            } else {
                $specialty = $request->specialty;
            }

            if ($request->qualification === 'null') {
                $qualification = Null;
            } else {
                $qualification = $request->qualification;
            }

            if ($request->address === 'null') {
                $address = Null;
            } else {
                $address = $request->address;
            }

            if ($request->area === 'null') {
                $area = Null;
            } else {
                $area = $request->area;
            }

            if ($request->areaOfResidence === 'null') {
                $areaOfResidence = Null;
            } else {
                $areaOfResidence = $request->areaOfResidence;
            }

            if ($request->dossierNumber === 'null') {
                $dossierNumber = Null;
            } else {
                $dossierNumber = $request->dossierNumber;
            }

            if ($request->notes === 'null') {
                $notes = Null;
            } else {
                $notes = $request->notes;
            }

            if ($request->periodOfResidence === 'null') {
                $periodOfResidence = Null;
            } else {
                $periodOfResidence = $request->periodOfResidence;
            }



            if ($request->contractExtensionPeriod === 'null') {
                $contractExtensionPeriod = Null;
            } else {
                $contractExtensionPeriod = $request->contractExtensionPeriod;
            }

            if ($request->phoneNumber === 'null') {
                $phoneNumber = Null;
            } else {
                $phoneNumber = $request->phoneNumber;
            }

            if ($request->email === 'null') {
                $email = Null;
            } else {
                $email = $request->email;
            }

            if ($request->user_id === 'null') {
                $userId = Null;
            } else {
                $userId = $request->user_id;
            }

            $person = Candidate::where('id', '=', $id)->first();

            $person->status_id = $request->status_id;
            $person->type_id = $request->type_id;
            $person->company_id = $request->company_id;
            $person->gender = $request->gender;
            $person->email = $email;
            $person->nationality = $request->nationality;
            $person->date = $request->date;
            $person->phoneNumber = $phoneNumber;
            $person->address = $address;
            $person->passport = $request->passport;
            $person->fullName = $request->fullName;
            $person->fullNameCyrillic = $request->fullNameCyrillic;
            $person->birthday = $request->birthday;
            $person->placeOfBirth = $request->placeOfBirth;
            $person->country = $request->country;
            $person->area = $area;
            $person->areaOfResidence = $areaOfResidence;
            $person->addressOfResidence = $request->addressOfResidence;
            $person->periodOfResidence = $periodOfResidence;
            $person->passportValidUntil = $request->passportValidUntil;
            $person->passportIssuedBy = $request->passportIssuedBy;
            $person->passportIssuedOn = $request->passportIssuedOn;
            $person->addressOfWork = $request->addressOfWork;
            $person->nameOfFacility = $request->nameOfFacility;
            $person->education = $education;
            $person->specialty = $specialty;
            $person->qualification = $qualification;
            $person->contractExtensionPeriod = $contractExtensionPeriod;
            $person->salary = $request->salary;
            $person->workingTime = $request->workingTime;
            $person->workingDays = $request->workingDays;
            $person->martialStatus = $request->martialStatus;
            $person->contractPeriod = $request->contractPeriod;
            $person->contractType = $request->contractType;
            $person->position_id = $request->position_id;
            $person->dossierNumber = $dossierNumber;
            $person->notes = $notes;
            $person->user_id = $userId;


            if ($request->hasFile('personPassport')) {
                Storage::disk('public')->put('personPassports', $request->file('personPassport'));
                $name = Storage::disk('public')->put('personPassports', $request->file('personPassport'));
                $person->passportPath = $name;
                $person->passportName = $request->file('personPassport')->getClientOriginalName();
            }


            if ($request->hasFile('personPicture')) {
                Storage::disk('public')->put('personImages', $request->file('personPicture'));
                $name = Storage::disk('public')->put('companyImages', $request->file('personPicture'));
                $person->personPicturePath = $name;
                $person->personPictureName = $request->file('personPicture')->getClientOriginalName();
            }


            if ($person->save()) {
                $newPerson = Candidate::with('position')->where('id', '=', $id)->first();
                return response()->json([
                    'success' => true,
                    'status' => 200,
                    'data' => $newPerson,
                ]);
            } else {
                return response()->json([
                    'success' => false,
                    'status' => 500,
                    'data' => [],
                ]);
            }
        } else {
            return response()->json([
                'success' => false,
                'status' => 401,
                'data' => [],
            ]);
        }
    }

    public function worker($id)
    {
        $worker = Candidate::where('id', '=', $id)->first();

        $worker->type_id = 2;
        $worker->status_id = 10;

        if ($worker->save()) {
            return response()->json([
                'success' => true,
                'status' => 200,
                'message' => 'Your change status from candidate to worker',
            ]);
        } else {
            return response()->json([
                'success' => false,
                'status' => 500,
                'message' => 'Something went wrong',
            ]);
        }
    }


    public function destroy($id)
    {
        $personDelete = Candidate::findOrFail($id);

        $files = File::where('candidate_id', '=', $id)->get();

        foreach ($files as $file) {
            if (isset($file->filePath)) {
                unlink(storage_path() . '/app/public/' . $file->filePath);
            }

            $file->delete();
        }
        $categoriesForCandidate = Category::where('candidate_id', '=', $id)->get();

        foreach ($categoriesForCandidate as $category) {
            $category->delete();
        }

        if ($personDelete->delete()) {
            return response()->json([
                'success' => true,
                'status' => 200,
                'message' => 'Proof! Your employ has been deleted!',
            ]);
        }
    }
}
