<?php

namespace App\Http\Controllers;

use App\Models\CompanyCategory;
use App\Traits\HasRolePermissions;
use App\Models\CompanyFile;
use App\Models\Role;
use App\Models\Permission;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use App\Services\File\FileOperationService;

class CompanyFileController extends Controller
{
    use HasRolePermissions;

    public function __construct(
        protected FileOperationService $fileService
    ) {}

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if (!$this->checkPermission(Permission::DOCUMENTS_CREATE)) {
            return response()->json(['error' => 'Insufficient permissions'], 403);
        }

        $companyFile = new CompanyFile();

        if (isset($request->autoGenerated)) {
            if ($request->hasFile('companyFile')) {
                $name = $this->fileService->uploadFile($request->file('companyFile'), 'companyFiles');
                $companyFile->filePath = $name;
            }
            $companyFile->fileName = $request->fileName;
        } else {
            if ($request->hasFile('companyFile')) {
                $name = $this->fileService->uploadFile($request->file('companyFile'), 'companyFiles');
                $companyFile->filePath = $name;
                $companyFile->fileName = $request->file('companyFile')->getClientOriginalName();
            }
        }
        $companyFile->company_category_id = $request->company_category_id;
        $companyFile->company_id = $request->company_id;

        if ($companyFile->save()) {
            return response()->json([
                'success' => true,
                'status' => 200,
                'message' => "Файлът \"{$companyFile->fileName}\" беше качен успешно",
                'data' => $companyFile
            ]);
        } else {
            return response()->json([
                'success' => false,
                'status' => 500,
                'message' => 'Грешка при качване на файла',
                'data' => $companyFile->errors()
            ], 500);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\CompanyFile  $companyFile
     * @return \Illuminate\Http\JsonResponse
     */
    public function show($id)
    {
        $user = Auth::user();

        if (!$this->checkPermission(Permission::DOCUMENTS_READ)) {
            return response()->json(['error' => 'Insufficient permissions'], 403);
        }

        $companyFiles = CompanyFile::where('company_id', '=', $id)->get();

        if ($this->isStaff()) {
            // Staff can see all categories
            $companyCategories = CompanyCategory::where('company_id', '=', $id)->get();
        } else {
            // Non-staff users see categories where:
            // 1. role_id matches their role, OR
            // 2. Their role is in allowed_roles array
            $userRoleId = $user->role_id;
            
            $companyCategories = CompanyCategory::where('company_id', '=', $id)
                ->where(function ($query) use ($userRoleId) {
                    $query->where('role_id', '=', $userRoleId)
                          ->orWhereJsonContains('allowed_roles', (string)$userRoleId)
                          ->orWhereJsonContains('allowed_roles', $userRoleId);
                })
                ->get();
        }

        return response()->json([
            'success' => true,
            'status' => 200,
            'files' => $companyFiles,
            'CompanyCategories' => $companyCategories,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\JsonResponse
     */
    public function update(Request $request, $id)
    {
        if (!$this->checkPermission(Permission::DOCUMENTS_UPDATE)) {
            return response()->json(['error' => 'Insufficient permissions'], 403);
        }

        $request->validate([
            'company_category_id' => 'nullable|integer|exists:company_categories,id',
        ]);

        $companyFile = CompanyFile::findOrFail($id);

        if ($request->has('company_category_id')) {
            $companyFile->company_category_id = $request->company_category_id;
        }

        if ($companyFile->save()) {
            return response()->json([
                'success' => true,
                'status' => 200,
                'message' => 'File updated successfully',
                'data' => $companyFile
            ]);
        }

        return response()->json(['error' => 'Update failed'], 500);
    }

    /**
     * Duplicate the specified resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\JsonResponse
     */
    public function duplicate(Request $request, $id)
    {
        if (!$this->checkPermission(Permission::DOCUMENTS_CREATE)) {
            return response()->json(['error' => 'Insufficient permissions'], 403);
        }

        $companyFile = CompanyFile::findOrFail($id);
        $newCategoryId = $request->input('company_category_id');
        $originalPath = $companyFile->filePath;
        
        $newPath = $this->fileService->copyFile($originalPath, 'companyFiles');
        
        if ($newPath) {
            $newFile = $companyFile->replicate();
            $newFile->filePath = $newPath;
            $newFile->company_category_id = $newCategoryId;
            $newFile->save();
            return response()->json([
                'success' => true, 
                'message' => 'File duplicated successfully',
                'data' => $newFile
            ]);
        }
        
        return response()->json(['error' => 'Copy failed'], 500);
    }

    public function downloadCompanyFile(CompanyFile $file)
    {
        $pathToFile = public_path('storage/' . $file->filePath);
        return response()->download($pathToFile);
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\CompanyFile  $companyFile
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (!$this->checkPermission(Permission::DOCUMENTS_DELETE)) {
            return response()->json(['error' => 'Insufficient permissions'], 403);
        }

        $companyFile = CompanyFile::findOrFail($id);
        $fileName = $companyFile->fileName;

        if ($companyFile->delete()) {
            if ($companyFile->filePath) {
               $this->fileService->deleteFile($companyFile->filePath);
            }

            return response()->json([
                'success' => true,
                'status' => 200,
                'message' => "Файлът \"{$fileName}\" беше изтрит успешно",
            ]);
        }

        return response()->json([
            'success' => false,
            'status' => 500,
            'message' => 'Грешка при изтриване на файла',
        ], 500);
    }
}
