<?php

namespace App\Http\Controllers;

use App\Models\Candidate;
use App\Traits\HasRolePermissions;
use App\Models\Category;
use App\Models\File;
use App\Models\Role;
use App\Models\Permission;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use ZipArchive;

class FileController extends Controller
{
    use HasRolePermissions;
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function index()
    {
        $documentsThatCanBeViewedByCompany = DB::table('files')
            ->join('categories', 'files.category_id', '=', 'categories.id')
            ->select('files.id', 'files.fileName', 'files.category_id', 'categories.nameOfCategory', 'files.company_restriction')
            ->where('files.fileName', 'like', 'ТД%')
            ->orWhere('files.fileName', 'like', 'ТРУДОВ%')
            ->orWhere('files.fileName', 'like', '%passport%')
            ->orWhere(function ($query) {
                $query->whereRaw('LOWER(categories.nameOfCategory) = LOWER(?)', ['ВИЗА']);
            })
            ->get();

        foreach ($documentsThatCanBeViewedByCompany as $document) {
            DB::table('files')
                ->where('id', $document->id)
                ->update(['company_restriction' => 0]);
        }

        return response()->json([
            'success' => true,
            'status' => 200,
            'data' => $documentsThatCanBeViewedByCompany
        ]);
    }

    public function downloadAllFile($id)
    {
        $candidate_id = $id;
        $candidate = Candidate::where('id', $candidate_id)->first();

        $files = File::where('candidate_id', $candidate_id)
            ->get(["filePath", "fileName"]);

        // Check if there are no files
        if ($files->isEmpty()) {
            return response()->json([
                'success' => false,
                'message' => 'Няма документи за този кандидат'
            ], 404);
        }

        // Check if any files actually exist on disk
        $existingFiles = [];
        foreach ($files as $file) {
            $filePath = public_path('storage/' . $file->filePath);
            if (file_exists($filePath)) {
                $existingFiles[] = $file;
            }
        }

        if (empty($existingFiles)) {
            return response()->json([
                'success' => false,
                'message' => 'Няма документи за този кандидат'
            ], 404);
        }

        $zip = new ZipArchive;
        $zipFileName = $candidate->fullName . '_documents.zip';
        $zipFilePath = storage_path('app/' . $zipFileName);

        if ($zip->open($zipFilePath, ZipArchive::CREATE | ZipArchive::OVERWRITE) === true) {
            foreach ($existingFiles as $file) {
                $filePath = public_path('storage/' . $file->filePath);
                $fileName = $file->fileName;
                $fileExtension = substr(strrchr($filePath, '.'), 1);
                $fileName .= '.' . $fileExtension;
                $zip->addFile($filePath, $fileName);
            }
            $zip->close();

            return response()->download($zipFilePath, $zipFileName);
        } else {
            return response()->json(['message' => 'Failed to create the zip file'], 500);
        }
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function store(Request $request)
    {
        $file = new File();

        if ($request->hasFile('file')) {
            Storage::disk('public')->put('files', $request->file('file'));
            $name = Storage::disk('public')->put('files', $request->file('file'));
            $file->filePath = $name;
        }

        $file->fileName = $request->fileName;
        $file->candidate_id = $request->candidate_id;
        $file->category_id = $request->category_id;
        $file->company_restriction = $request->company_restriction ?? 1;
        $file->autoGenerated = $request->autoGenerated;
        $file->deleteFile = $request->deleteFile;


        if ($file->save()) {
            return response()->json([
                'success' => true,
                'status' => 200,
                'message' => "Файлът \"{$file->fileName}\" беше качен успешно",
                'data' => $file
            ]);
        } else {
            return response()->json([
                'success' => false,
                'status' => 500,
                'message' => 'Грешка при качване на файла',
                'data' => $file->errors()
            ], 500);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\File  $file
     * @return \Illuminate\Http\Response
     */
    public function downloadFile(File $file)
    {
        $pathToFile = public_path('storage/' . $file->filePath);
        $extension = pathinfo($file->filePath, PATHINFO_EXTENSION);
        $fileName = $file->fileName;

        // Add extension if not already present
        if ($extension && !str_ends_with(strtolower($fileName), '.' . strtolower($extension))) {
            $fileName .= '.' . $extension;
        }

        return response()->download($pathToFile, $fileName);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\File  $file
     * @return \Illuminate\Http\JsonResponse
     */
    public function show($id)
    {
        $userRoleId = Auth::user()->role_id;

        $categoriesQuery = Category::where('candidate_id', $id);

        if ($this->isStaff()) {
            $categoriesQuery->whereNull('candidate_id')->orWhere('candidate_id', $id);
        } elseif ($userRoleId == 3) {
            $categoriesQuery->where('role_id', 3)->orWhere('role_id', 4)->where('candidate_id', $id);
        } elseif ($userRoleId == 4) {
            $categoriesQuery->where('role_id', 4)->where('candidate_id', $id);
        } elseif ($userRoleId == 5) {
            $categoriesQuery->whereIn('role_id', [3, 4, 5])->where('candidate_id', $id);
        }

        $categories = $categoriesQuery->orderBy('id', 'asc')->get();
        $categoriesIds = $categories->pluck('id');
        $filesQuery = File::with('category')->where('candidate_id', $id);

        if ($userRoleId == 3 || $userRoleId == 5) {
            $filesQuery->where(function ($query) {
                $query->orWhereHas('category', function ($q) {
                    $q->where('role_id', '!=', 1)
                        ->orWhere('role_id', '!=', 2);
                });
            });
        }

        if ($userRoleId == 4) {
            $filesQuery = File::where('candidate_id', $id)
                ->whereIn('category_id', $categoriesIds);
        }

        $files = $filesQuery->get();

        $candidatePassport = $this->isStaff() ? Candidate::where('id', $id)->value('passportPath') : null;

        return response()->json([
            'success' => true,
            'status' => 200,
            'files' => $files,
            'categories' => $categories,
            'candidatePassport' => $candidatePassport,
        ]);
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\File  $file
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, File $file)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\File  $file
     * @return \Illuminate\Http\JsonResponse|\Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = Auth::user();
        $fileDelete = File::findOrFail($id);

        // Staff with DOCUMENTS_DELETE permission can delete any document
        if ($this->checkPermission(Permission::DOCUMENTS_DELETE)) {
            return $this->deleteFile($fileDelete);
        }

        // Agents can only delete documents for their own candidates
        if ($user->hasRole(Role::AGENT)) {
            $candidate = Candidate::find($fileDelete->candidate_id);
            if ($candidate && $candidate->agent_id === $user->id) {
                return $this->deleteFile($fileDelete);
            }
        }

        return response()->json(['error' => 'Insufficient permissions'], 403);
    }

    /**
     * Helper method to delete file and remove from storage
     */
    private function deleteFile(File $file)
    {
        $fileName = $file->fileName;

        if ($file->delete()) {
            $filePath = storage_path() . '/app/public/' . $file->filePath;
            if (file_exists($filePath)) {
                unlink($filePath);
            }

            return response()->json([
                'success' => true,
                'status' => 200,
                'message' => "Файлът \"{$fileName}\" беше изтрит успешно",
            ]);
        }

        return response()->json([
            'success' => false,
            'status' => 500,
            'message' => 'Грешка при изтриване на файла',
        ], 500);
    }
}
