<?php

namespace App\Http\Controllers;

use App\Models\Candidate;
use App\Traits\HasRolePermissions;
use App\Models\File;
use App\Models\Position;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;


class PositionController extends Controller
{
    use HasRolePermissions;
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function index()
    {

            $allPositions = Position::with(['documents', 'files'])->get();

            return response()->json([
                'success' => true,
                'status' => 200,
                'data' => $allPositions,
            ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if ($this->isStaff()) {

            $jobPosition = new Position();

            $jobPosition->NKDP = $request->NKDP;
            $jobPosition->jobPosition = $request->jobPosition;


            if ($request->hasFile('positionDocument')) {
                $name = Storage::disk('public')->put('jopPosition', $request->file('positionDocument'));
                $jobPosition->positionPath = $name;
                $jobPosition->positionName = $request->file('positionDocument')->getClientOriginalName();
            }


            if ($jobPosition->save()) {
                return response()->json([
                    'success' => true,
                    'status' => 200,
                    'data' => $jobPosition,
                ]);
            } else {
                return response()->json([
                    'success' => false,
                    'status' => 500,
                    'data' => []
                ]);
            }
        } else {
            return response()->json([
                'success' => false,
                'status' => 403,
                'data' => []
            ]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Position  $position
     * @return \Illuminate\Http\Response
     */
    public function show(Position $position)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Position  $position
     * @return \Illuminate\Http\Response
     */
    public function edit(Position $position)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Position  $position
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if ($this->isStaff()) {

            $jobPosition = Position::where('id', '=', $id)->first();

            $jobPosition->NKDP = $request->NKDP;
            $jobPosition->jobPosition = $request->jobPosition;

            if ($request->hasFile('positionDocument')) {
                $name = Storage::disk('public')->put('jopPosition', $request->file('positionDocument'));
                $jobPosition->positionPath = $name;
                $jobPosition->positionName = $request->file('positionDocument')->getClientOriginalName();
            }


            if ($jobPosition->save()) {

            $candidateWithThisJob = Candidate::where('position_id', '=', $jobPosition->id)->get();

                foreach ($candidateWithThisJob as $candidate) {

                    $file = new File();
                    $file->candidate_id = $candidate->id;
                    $file->category_id = 8;
                    $file->fileName = $jobPosition->positionName;
                    $file->filePath = $jobPosition->positionPath;
                    $file->autoGenerated = 1;
                    $file->deleteFile = 2;


                    $file->save();
                }

                return response()->json([
                    'success' => true,
                    'status' => 200,
                    'data' => $jobPosition,
                ]);
            } else {
                return response()->json([
                    'success' => false,
                    'status' => 500,
                    'data' => []
                ]);
            }
        } else {
            return response()->json([
                'success' => false,
                'status' => 403,
                'data' => []
            ]);
        }
    }


    public function destroyDocumentForPosition($id)
    {
        if ($this->isStaff()) {

            $fileDelete = Position::findOrFail($id);

           $candidateWithThisJobPosition = Candidate::where('position_id', '=', $id)->get();

            foreach ($candidateWithThisJobPosition as $candidate) {

                $fileForDelete = File::where('candidate_id', '=', $candidate->id)->where('deleteFile','=',2)->get();
                foreach ($fileForDelete as $file) {
                    $file->delete();
                }
            }



            $fileDelete->positionName = Null;
            $fileDelete->positionPath = Null;

            if ($fileDelete->save()) {
                return response()->json([
                    'success' => true,
                    'status' => 200,
                    'message' => 'Proof! Your file has been deleted!',
                ]);
            }
        } else {
            return response()->json([
                'success' => true,
                'status' => 401,
                'message' => 'You dont have access',
            ]);
        }
    }


    public function destroy($id)
    {
        if ($this->isStaff()) {

            $position = Position::where('id', '=', $id)->first();

            if ($position->delete()) {
                return response()->json([
                    'success' => true,
                    'status' => 200
                ]);
            }
        } else {
            return response()->json([
                'success' => false,
                'status' => 403
            ]);
        }
    }

    /**
     * Get documents for a specific position
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function getDocuments($id)
    {
        $position = Position::with('documents')->find($id);

        if (!$position) {
            return response()->json([
                'success' => false,
                'status' => 404,
                'message' => 'Position not found'
            ], 404);
        }

        return response()->json([
            'success' => true,
            'status' => 200,
            'data' => $position->documents
        ]);
    }

    // ========== REQUIRED DOCUMENTS (position_documents) ==========

    /**
     * Add required document name
     */
    public function addRequiredDocument(Request $request, $id)
    {
        if (!$this->isStaff()) {
            return response()->json(['success' => false, 'status' => 403, 'message' => 'Unauthorized'], 403);
        }

        $position = Position::find($id);
        if (!$position) {
            return response()->json(['success' => false, 'status' => 404, 'message' => 'Position not found'], 404);
        }

        $document = $position->documents()->create([
            'name' => $request->name,
        ]);

        return response()->json(['success' => true, 'status' => 200, 'data' => $document]);
    }

    /**
     * Delete required document
     */
    public function deleteRequiredDocument($positionId, $documentId)
    {
        if (!$this->isStaff()) {
            return response()->json(['success' => false, 'status' => 403, 'message' => 'Unauthorized'], 403);
        }

        $document = \App\Models\PositionDocument::where('id', $documentId)
            ->where('position_id', $positionId)
            ->first();

        if (!$document) {
            return response()->json(['success' => false, 'status' => 404, 'message' => 'Document not found'], 404);
        }

        $document->delete();
        return response()->json(['success' => true, 'status' => 200, 'message' => 'Document deleted']);
    }

    // ========== FILES (position_files) ==========

    /**
     * Upload file for position
     */
    public function uploadFile(Request $request, $id)
    {
        if (!$this->isStaff()) {
            return response()->json(['success' => false, 'status' => 403, 'message' => 'Unauthorized'], 403);
        }

        $position = Position::find($id);
        if (!$position) {
            return response()->json(['success' => false, 'status' => 404, 'message' => 'Position not found'], 404);
        }

        if (!$request->hasFile('file')) {
            return response()->json(['success' => false, 'status' => 400, 'message' => 'No file provided'], 400);
        }

        $file = $request->file('file');
        $fileName = $file->getClientOriginalName();
        $filePath = Storage::disk('public')->put('position_files', $file);

        $positionFile = $position->files()->create([
            'file_name' => $fileName,
            'file_path' => $filePath,
        ]);

        return response()->json(['success' => true, 'status' => 200, 'data' => $positionFile]);
    }

    /**
     * Delete file
     */
    public function deleteFile($positionId, $fileId)
    {
        if (!$this->isStaff()) {
            return response()->json(['success' => false, 'status' => 403, 'message' => 'Unauthorized'], 403);
        }

        $file = \App\Models\PositionFile::where('id', $fileId)
            ->where('position_id', $positionId)
            ->first();

        if (!$file) {
            return response()->json(['success' => false, 'status' => 404, 'message' => 'File not found'], 404);
        }

        // Delete from storage
        if (Storage::disk('public')->exists($file->file_path)) {
            Storage::disk('public')->delete($file->file_path);
        }

        $file->delete();
        return response()->json(['success' => true, 'status' => 200, 'message' => 'File deleted']);
    }
}
