<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class File extends Model
{
    use HasFactory;

    protected $fillable = [
        'candidate_id',
        'contract_id',
        'arrival_id',
        'category_id',
        'filePath',
        'fileName',
        'autoGenerated',
        'deleteFile',
        'company_restriction',
    ];

    public function candidates()
    {
        return $this->belongsTo(Candidate::class,'candidate_id');
    }

    public function contract()
    {
        return $this->belongsTo(CandidateContract::class, 'contract_id');
    }

    public function category()
    {
        return $this->belongsTo(Category::class,'category_id');
    }
}
